version: "3.9"
services:
    postgres:
      env_file:
        - .env.local
      image: postgres
      ports:
        - "${POSTGRES_EXTERNAL_PORT}:5432"

    webserver:
      build: docker/nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${NGINX_EXTERNAL_HTTP_PORT}:80"

    php-fpm:
      build: docker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
